use_frameworks!

platform :ios, '9.0'

target 'JKFlutterKits_Example' do
  pod 'JKFlutterKits/iOS', :path => '../'

  target 'JKFlutterKits_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
